name: Primary
on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    name: Code quality Checks
    
    steps:
     - uses: actions/checkout@v1
     - name: Danger
       uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.9.1
       with:
            args: --failOnErrors --no-publish-check
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  UnitTests:
    name: Unit Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
          bundle install
     
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
         xcode-version: latest-stable
             
    - name: Run tests
      run: |
         bundle exec fastlane unit_tests
